language: php

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

notifications:
  email: team@swoole.com

env:
  global:
    - secure: "Mqg9ifSV0BLv2TIBw/x64aEuB8Y5aPXwXg7xAOq08oPlHBYSBgSYxroJL5PXs0fe7PszZF20bUBinwmEXYQzqgP/40Y1kmq/kfTsDXwTOc9qbAbA1pWvH+Sk1kDP5MLJRPWBCkqctyFd0I0u0SdzT1fgSqirqEz2bMnbAUVpSvo="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "swoole/swoole-src"
      description: "Build submitted via Travis CI"
    notification_email: mikan.tenny@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

#Compile
before_script:
    - apt-get install libnghttp2
    - phpize && ./configure --enable-openssl --enable-http2 --enable-async-redis && make clean && make && make install
    - echo -e '\nextension=swoole.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - cd tests && travis_wait ./start-tests.sh
    - exit 0


